### PR TITLE
Styled hubspot form and embeded in contact us page

### PR DESCRIPTION
**Pull request by cristyanc**
## What does this PR do?
- Replaced 'contact us' form with Hubspot embedded form
- Form was styled in Hubspot

## How to test
- Navigate to 'contact us' and submit the form. At the moment form is configured to display a thank you message.

### CODE REVIEW

**Comment by cristyanc** [comment]
This closes #30

**Comment by jamiefolsom** [comment]
Looking good so far @cristyanc. We should style the thank you page as well. And let's put the name fields in the order: first name then last name, instead of the reverse.

**Comment by cristyanc** [comment]
I created  issue #50 to format the thank you message

**Comment by jamiefolsom** [comment]
OK @cristyanc, why don't you push commits to this branch (`cc/contact-page`) to add that thank you page. Then reopen this PR for review, and when it's ready, we can rebase/squash and merge. Sound good?

**Pull request merged**
