### PR TITLE
Added Makoto to the team page.

### PR DESCRIPTION
**Pull request by jamiefolsom**
- Needs:
  - Headshot
  - Bio
  - Github username

### CODE REVIEW

**Comment by jamiefolsom** [comment]
@mkobayashi21 would you rebase this against `gh-pages` and update it with the correct content? Got to get you on the website! 😄

**Comment by mkobayashi21** [comment]
The addition of the face pic overlaps with #27. I edited the picture so it may be better to have another PR with just David's bio and pic.

**Comment by jamiefolsom** [comment]
Ah, and sure -- I will remove your pic from the other PR -- thanks.

**Comment by mkobayashi21** [comment]
For some reason I can't put you as a reviewer; I tried taking you off of the assignees but no luck. Would you be willing to look over the changes anyway? I can make myself a reviewer so I can merge when you are done.

**Comment by jamiefolsom** [comment]
Looks good! 👍

**Comment by jamiefolsom** [comment]
@mkobayashi21 oops -- one issue -- my name is spelled "Jamie" 😉 Fix that, and feel free to merge and push. Thanks!

**Comment by jamiefolsom** [comment]
@mkobayashi21 -- remember to `git rebase -i origin/gh-pages` and squash commits before merging to `gh-pages`. Let me know if you want a refresher on that process.

**Pull request merged**
