### PR TITLE
Fixed logo, nav, favicon issues

### LINKED ISSUE #58: Logo issues
- [x] Replace favicon with white P version
- [x] Make the PSS logo larger at top in navigation, 30-40px or so.
- [x] Remove the "Home" link
- [x] Make the logo a link on all pages.

### PR DESCRIPTION
**Pull request by cristyanc**
## What does this PR do?
- Replaced favicon with white "P"
- Make top nav logo bigger, fixe all related media queries, added custom SCSS variables
- Update global navigation removed home link
- Updated gulpfile to facilitate debugging SCSS
- This closes #58

## How to test?
- Website global top navigation items without the home link, more prominent logo, etc.

### CODE REVIEW

**Comment by cristyanc** [comment]
All set, I uploaded the file to the root directory.

**Comment by jamiefolsom** [comment]
Another change request. Nav height is greater (and better-looking) before this PR. Let's revert the height of the nav itself, and make sure links are vertically centered. 

Old nav is 71px (preferred height): 

image


New nav is 55px

image

**Comment by cristyanc** [comment]
Ok, I will reverse that to be centered. FYI, It looks odd on small screens since the items won't align with the logo.

**Comment by cristyanc** [comment]
All Set!

**Pull request merged**
